config/routes.rb
Rails.application.routes.draw do
  resources :terms

  resources :comments

  root 'visitors#index'
  devise_for :users
  resources :users

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/term.rb
class Term < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  geocoded_by :address
  after_validation :geocode
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.active
    where(status: "active") 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    users_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @comment = Comment.new
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:name, :comment)
    end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @terms = Term.all
    respond_with(@terms)
  end

  def show
    respond_with(@term)
  end

  def new
    @term = Term.new
    respond_with(@term)
  end

  def edit
  end

  def create
    @term = Term.new(term_params)
    @term.save
    respond_with(@term)
  end

  def update
    @term.update(term_params)
    respond_with(@term)
  end

  def destroy
    @term.destroy
    respond_with(@term)
  end

  private
    def set_term
      @term = Term.find(params[:id])
    end

    def term_params
      params.require(:term).permit(:agreement)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  respond_to :html, :xml, :json

  def index
    @users = User.active
    @hash = Gmaps4rails.build_markers(@users) do |user, marker|

      marker.lat user.latitude
      marker.lng user.longitude
      marker.title user.status
      user_link = view_context.link_to user.title, user_path(user)
      marker.infowindow "<h4><u>#{user_link}</u></h4><i>#{user.address}</i>"

    end
  end

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1 align=center>ShovelMeOut</h1>
<p align=center> If your car's burried, find someone to help! </p>
<p align=center> If you want to earn cash, find buried cars on the map </p>
<h4> Leave us Feedback! </h4>
<%= render 'form' %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.name %></td>
        <td><%= comment.comment %>|</td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @comment.name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Map', users_path %></li>
  <li><%= link_to 'How It Works', comments_path %></li>
  <li><%= link_to 'Terms and Conditions', terms_path %></li>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
  <li><%= link_to 'How It Works', comments_path %></li>
  <li><%= link_to 'Terms and Conditions', terms_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ShovelMeOut" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ShovelMeOut" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/terms/_form.html.erb
<%= form_for(@term) do |f| %>
  <% if @term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@term.errors.count, "error") %> prohibited this term from being saved:</h2>

      <ul>
      <% @term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :agreement %><br>
    <%= f.text_field :agreement %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/terms/edit.html.erb
<h1>Editing term</h1>

<%= render 'form' %>

<%= link_to 'Show', @term %> |
<%= link_to 'Back', terms_path %>

app/views/terms/index.html.erb
<div class="authform">
  <fieldset>
  <h1 align=center>Terms and Conditions</h1>
  <p align=right; style="width:200px;" >By using this application, you agree to share your location and email with other users. You may enter your phone number for faster response times if you wish, and remember that this information can be seen by other registered users.</p> 
  </fieldset>
</div>

app/views/terms/new.html.erb
<h1>New term</h1>

<%= render 'form' %>

<%= link_to 'Back', terms_path %>

app/views/terms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agreement:</strong>
  <%= @term.agreement %>
</p>

<%= link_to 'Edit', edit_term_path(@term) %> |
<%= link_to 'Back', terms_path %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<h3 align=center>Buried in the Blizzard </h3>
<br>
<div style='width: 300px; margin-left:auto; margin-right:auto;'>
  <div id="map" style='width: 300px; height: 400px; margin-left:auto; margin-right:auto;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>
<p>Title: <%= @user.title if @user.title %></p>
<p>Status: <%= @user.status if @user.status %></p>

app/views/visitors/index.html.erb
<div class="authform">
  <fieldset>
  <h3 align=center>ShovelMeOut</h3>
  <img src="vin.jpg" style="align:float">
  <br /> 
  <div align="center">
    <a href="users/sign_in"><input type="button" class ='button' value="Log In!"/></a>
    <a href="users/sign_up"><input type="button" class ='button' value="Sign Up"/></a>
</div>
</fieldset>
</div>